# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 516cea9d0c912502a06668a9414717681064e61788b00d376b9bcbea929f935d950987fcf698c53e7ff2ccddc90119bdc6ba465ee8c83413a8ceaf2b8dbeaddd

test:
  secret_key_base: c19e0f99e88571ab1a4e04bb78aacc99baca7c582eeec697124bf4825b06e45c007931c8424e2fa01114758b1434e76a0cb62187517b334ff8891dbeafb715ad

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
